FROM node:16-alpine  
  
WORKDIR /app  
  
ENV DATABASE_HOST=postgresdb
ENV DATABASE_PORT=5432  
ENV DATABASE_USERNAME=postgres
ENV DATABASE_PASSWORD=foo
ENV DATABASE_NAME=postgres  
  
COPY package*.json ./  
RUN npm install  
# Ensure this line is present to copy all files
COPY . .  

# Expose the port your app runs on 
EXPOSE 3006
  
#ENTRYPOINT ["node", "src/index.js"]

# Use nodemon in development mode 
CMD ["npm", "run", "dev"]