# version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: foo
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3003:3006"
    container_name: userapi
    environment:
      DATABASE_HOST: postgresdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: foo
      DATABASE_NAME: postgres
    networks:
      - mynetwork
    depends_on:
      - postgres

networks:
  mynetwork:
    external: true

